# Generated by Django 6.1 on 2026-09-08 18:16

import instagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/', validators=[instagram.models.validate_image_extension]),
        ),
    ]
