# Generated by Django 6.1.1 on 2026-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing'), ('FD', 'Food')], default='EL', max_length=2),
        ),
    ]
