# Generated by Django 6.1.1 on 2026-09-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_stock_to_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
